development:
  adapter: postgresql
  encoding: unicode
  database: rsvp_development
  pool: 5
  username: kuhar
  password: kuhar
  
test:
  adapter: postgresql
  encoding: unicode
  database: rsvp_development
  pool: 5
  username: kuhar
  password: kuhar

