# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e33a09e39c4f835b8f6b05a206013b338700eca5987262e1d817046d18a04f2093cb6b78c209da6b3ad2f11459f66d67da2524c1496417c33325b67c1fc1601f

test:
  secret_key_base: d7210186a21806a2bf543dde9a682cdb9fd47d513bd76332604c623bee1478623153e7495ac1c694b279f920dc9498c34aa901b577ca2f8ccdd580efcaa84807

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
